name = "ForwardMethods"
uuid = "5fe2550f-d27e-4649-9aea-fdf9a83a1aa9"
authors = ["Curt Da Silva <curt.dasilva@gmail.com>"]
version = "1.5.2"

[deps]
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
MacroUtilities = "274a0f0b-05f4-4024-87ff-de4a5b524b4f"

[compat]
MLStyle = "0.4"
MacroUtilities = "1.16"
julia = "1.6"
